### ISSUE TITLE
scale up (vertically): swap out for larger nodes in an opstrace instance via the CLI

### ISSUE THREAD

**Issue by triclambert** [opstrace/opstrace#1028]
Investigate how we can replace all nodes in an opstrace instance with larger ones via the CLI.  (Can probably omit scaling down to smaller nodes.)

Depends on moving to managed EKS nodes for AWS.

**Comment by jgehrcke** [comment]
Okay, this is quite solution-focused.

If anticipated load changes and if initial instance dimensions turn out to be 'wrong' then maybe it is fair to tolerate downtime and simply set up a fresh Opstrace instance with a different `node_type`, re-using the state of the previous one ('hibernation mode').

Would love to see a little bit of a problem and goal statement, and context.

A few thinking points:
-  There might be the assumption in here that we cannot have downtime. That comes along with _high robustness expectations_ -- building this so that it's robust and always well-tested: a lot of work.
- This heavily overlaps with fault tolerance topics.
- If we want to build this: before making this a first-class documented operation let's maybe wait and see how our thoughts evolve for an interface definition (skeptical w.r.t. a new sub command).
- To elaborate on the last point: this is maybe not completely orthogonal to the 'upgrade' operation where an instance config file is provided (which defines a node type). There is an outstanding question: which instance config parameters are allowed to be changed during an upgrade? Maybe `node_count` and node type will be among those, in the future.

> Depends on moving to managed EKS nodes for AWS.

I suppose with that we mean that the auto-scaling group approach does not allow for adding nodes of a different instance type, whereas with the managed node groups for EKS one can add more than one node group to an EKS cluster (and that is the mechanism how one can have a heterogeneous set of instance types in the same EKS cluster):

> You can add a managed node group to new or existing clusters using the Amazon EKS console, eksctl, AWS CLI; AWS API, or infrastructure as code tools including AWS CloudFormation. Nodes launched as part of a managed node group are automatically tagged for auto-discovery by the Kubernetes cluster autoscaler. You can use the node group to apply Kubernetes labels to nodes and update them at any time.

(https://docs.aws.amazon.com/eks/latest/userguide/managed-node-groups.html)

**Comment by triclambert** [comment]
> Would love to see a little bit of a problem and goal statement, and context.

The short of it is that today we scale up manually, and it is tedious and error prone.  Solving this with code would be preferable to that.  

Surely, there are many things to consider, but this is definitely meant to be well-scoped and short.

**Comment by jgehrcke** [comment]
> The short of it is that today we scale up manually, and it is tedious and error prone. Solving this with code would be preferable to that.

Thanks for clarification. Let's make this an internal 'recipe' then instead of "let's build an official, stable interface" (which is "via the CLI" made it sound like).

**Comment by MatApple** [comment]
I think it's a good idea to start brainstorming how we can make this easier for the end-user. The goal for this ticket would be to have a user-friendly method of changing the machine type. In most customer deployments, we've had to readjust the machine type as data requirements change. How we do it is up for debate! Perhaps it's through hibernation (recreate everything but the S3 buckets). This could be a sequence of steps for the end-user, but I could imagine it might just be 2-3 steps (hibernate existing instance, create a new instance with the new machine type that attaches to hibernated buckets, etc)

**Comment by triclambert** [comment]
It doesn't _have_ to be some internal 'recipe'...  "via the CLI" was meant to suggest doing it properly with code, one way or another.

> How we do it is up for debate! Perhaps it's through hibernation

💯   I do think hibernation can a good solution.  It is also useful for other reasons.
