### ISSUE TITLE
Add support for setting arbitrary tags on resources

### ISSUE THREAD

**Issue by blarghmatey** [opstrace/opstrace#1339]
## Current Behavior / Proposed Behavior
Currently the only tag that can be set is the `env_label`. It would be useful to expose an attribute under the `aws` or `gcp` configuration objects that accepts a mapping of tag key/value pairs to set on the resources created by OpsTrace.

## Context
The immediate reason for my purposes is to allow for cost allocation in the AWS billing reports, but there are many uses for tagging policies within an organization.

## Possible Technical Solution
Allow setting a mapping of key/value pairs under the `aws` and `gcp` configuration blocks that are set as tags on any resource that supports application of tags during creation or updates.

## Alternatives Considered
The alternative is to write a script that enumerates all of the resources in the opstrace created environment and applying the tags in a post-hoc fashion. This is certainly possible, but a bit suboptimal from a UX perspective.

**Comment by triclambert** [comment]
@blarghmatey, thanks for opening this issue!

Regarding tagging Opstrace-created resources, we have a working list of areas where we do not yet apply tags.  So there is some foundational work to be done first as well.

#### tag-on-create supported by aws, not created by installer, but by cluster or otherwise implicitly
- [ ] network acl (where/how are those created?)
- [ ] network interface
- [ ] volumes (disks)
- [ ] ELBs

#### tag-on-create not supported by aws?
- [ ] launch configuration
- [ ] EC2 elastic IP address (docs)
- [ ] S3 buckets
- [ ] IAM instance profile: can encode in name, api docs

Regarding cost attribution in the short term—we already recommend running Opstrace in an isolated account for reliability. This will implicitly allow for complete cost attribution.  Is that possibly an option for you?
