### ISSUE TITLE
cortex: Avoid returning 500-599 errors to remote_write clients

### ISSUE THREAD

**Issue by nickbp** [opstrace/opstrace#1409]
There are scenarios where Cortex can be overrun by push client requests. The server starts to return 500 errors, which the clients treat as retryable. The retries themselves can then prevent the clients from ever catching up, so they flood the server continuously. A small batch of 500 errors can then feed on itself and grow into an indefinite outage.

In this example, we can see 500 errors greatly outpacing other responses. The 500 errors are considered "retryable", while the 400 errors are due to the requested data being too old. There's even a gap in the middle of the chart where system metrics are being blocked by the thundering herd of retries, caused by global distributor queues filling up:
![134001156-d019639a-0363-43a9-a5ea-9f0d5f14f2c1](https://user-images.githubusercontent.com/35933/134093512-52fa3b73-4fe1-47c7-b27b-6b2c5ee53f18.png)

For debugging the current behavior, we can look at the Prometheus `remote_write` [HTTP error handling](https://github.com/prometheus/prometheus/blob/e582e907f8a97ffae27123b9632a254e5018a4a6/storage/remote/client.go#L233-L246) and [retry handling](https://github.com/prometheus/prometheus/blob/e582e907f8a97ffae27123b9632a254e5018a4a6/storage/remote/queue_manager.go#L1217-L1267):
- 500-599: retry after `remote_write.queue_config.min_backoff` (with expontential backoff up to `remote_write.queue_config.max_backoff`)
- 429 (if `remote_write.queue_config.retry_on_http_429` is enabled): retry after provided `Retry-After` header duration, or `min_backoff` -> `max_backoff` as above
- else: don't retry

The retry logic itself defaults to waiting `min_backoff=30ms` on the first retry, up to `max_backoff=100ms` on following retries. Each batch of `max_samples_per_send=500` has up to `batch_send_deadline=5s` to get sent. It looks like the default used to be `max_samples_per_send=100` but people were saying that [this was too low](https://github.com/prometheus/prometheus/issues/5166).

As a result, a _stock prometheus config_ could spend up to 5s reattempting a batch every few ms before finally giving up and moving to the next batch. Not exactly great behavior if you're trying to catch up after an outage. If server latency is high then the number of retries would go down - but it still means that Prometheus probably wouldn't ever catch up unless it's handling a trivial amount of series. When looking into this I wasn't expecting the retry loop to go that hard, I was picturing like 3-5 attempts max - who has metrics that are worth as many as 50 retries over 5s!?

In this environment there isn't a way for the clients to "move on" and stop retrying old data, since they are so adamant on retrying everything. On the server side of things, it's hard to plan for this because the ambient traffic can look fine until a hiccup or outage causes the Cortex distributor queues to fill, when then results in 500 errors. At this point things can quickly enter a retry death spiral. Push traffic that was previously arriving every 30s or 60s will suddenly start occurring every 50-100ms.

To short-circuit this and allow everyone to "move past" an outage, we can avoid ever telling Prometheus to retry - or at a technical level, we can remap any 5xx (or arguably even 429) errors to a different non-retryable error (thinking 4xx range). It does mean that there can be gaps in the data due to brief 500 outages, since the data won't be resubmitted, but that's better than long scenarios where nobody is able to catch up.

**Comment by nickbp** [comment]
Given the prior history with enabling retries on 429 errors in https://github.com/opstrace/opstrace/issues/464 I'm actually thinking we should continue having the 429->503 mapping, and then effectively add 5xx->409 mapping to that. In practice that should mean that when the server is doing fine, it will return 429->503 errors and clients will retry, but if the server is doing poorly, it will return 500->409 errors and clients will not retry.

As seen in the above scenario chart we aren't seeing any 429 nor 503 errors so keeping that behavior as-is shouldn't cause problems with the "runaway retries" scenario described here.

**Comment by nickbp** [comment]
Fixed via 5xx->409 remapping in `cortex-api`. Note that the existing 429->503 mapping remains since that's for a different situation.

**Comment by jgehrcke** [comment]
### Opinion on disabling retry: for now ok, but not in the long run

> we can avoid ever telling Prometheus to retry

For today I can agree with this pretty brutal decision-making! Thanks for just doing this, for taking action also w/o waiting for feedback :).

However: I think that we should prioritize finding a different approach. I am confident that there is a way to get us closer to the 'best of both worlds': auto-healing the equilibrium state transient issues, and also surviving outages in a controlled fashion.

We also need to think about the next release. This is a pretty significant change in behavior that is difficult to write about in terms of what the ultimate goal is. Maybe we want to back out of that again before the next release (maybe not!).

(Nick, I know you know this -- just for completeness:) In the equilibrium state of a well-working distributed system there is a non-zero transient error rate. Retrying is the mechanism as of which these transient errors do not immediately result in missing samples. In other words, retrying does a lot of auto-healing and it's doing a lot of good. This patch disables that mechanism.  That worsens the situation for a normally operating system.

> It does mean that there can be gaps in the data due to brief 500 outages, since the data won't be resubmitted, but that's better than long scenarios where nobody is able to catch up.

Right. It is important to also think of the scenarios in the spectrum between the super low error rate (one extreme case), and the full outage (another extreme case). Here is an example of a situation where the error rate was largish but low enough, and retrying resulted in no samples being lost:

![Screenshot from 2021-09-21 10-27-29](https://user-images.githubusercontent.com/265630/134137999-bce4b41d-1440-44f8-a76f-3893b267b9ed.png)

The error rate shown in the plot provides an idea about how many samples would have gone missing w/o the retrying behavior. One might say that the scenario shown in the screenshot is pathological because of the rather constant error rate.

Side note: this topic raises the interesting question about the importance of the individual data point / sample. In case of metrics, how important is the individual sample? Let's maybe think beyond the initial, intuition-driven response. Let's think about use cases and extreme cases.

### Quick comment on retrying behavior

> As a result, a stock prometheus config could spend up to 5s reattempting a batch every few ms before finally giving up and moving to the next batch. 

No. One problem with the Prometheus retrying parameterization is that there is no stop criterion! Not based on retry count, not based on on retry time, not based on sample age. Retrying continues until the request fails permanently (4xx) or succeeds.

`batch_send_deadline` is documented with "Even if the queued shards has not reached max_samples_per_send, a request will be sent..."

### Retry stop criterion in pusher prom: still needs to be implemetned

I very much agree with @csmarchbanks (https://github.com/prometheus/prometheus/issues/7912#issuecomment-737544041 and https://groups.google.com/g/prometheus-developers/c/2PEY4o5tgoI/m/Z5e8JxNIAwAJ) that sample age is a meaningful stop criterion. 

I think in case of the outage that led to this patch here, this max age concept would have been the 'better' short-circuit, and the correct approach. (I still think that the distributors were mainly occupied with rejecting too-old samples -- samples that the client _can know_ are too old, and not even try to send in the first place).

### Replaying old data after N-minute outage: specify requirements, test, have confidence.

This topic clearly has a lot to do with capacity planning and defining explicit requirements.

Here is a requirement that I would like us to look at: **Pushing end and receiving end should be tuned to each other so that the system can recover from an N minutes unavailability of the receiving end, without losing data.**

Think N = 60 if you'd like to, just to entertain the brain.

To fulfill that requirement the ingest system needs to be able to ingest samples at a rate significantly higher than the equilibrium ingest rate. So that the 'catch up phase' is short.

Example goal: "replaying 60 minutes worth of metrics data should take 10 minutes" -> during the catch-up phase, the ingest system must be able to ingest six times as much push throughput as in normal times.

The "large headroom paradigm" that I wrote about in our Wiki easily enables this. Should be the default. Of course this creates cost. If the cost is too large and 'old data' is not valuable enough, it makes a lot of sense to deviate.

After all, this should be the choice of the user. The user needs to say how large N should be, and we need to be able to say how much that N costs.

The being-able-to-recover-from-an-N-minutes-outage scenario can be nicely specified, and nicely tested. And as long as it's not systematically tested it's broken. **To me, that's the best argument for disabling retrying today as you did it @nickbp.**

### Retrying parameters: pusher prom config needs a lot of tuning

The being-able-to-recover-from-an-N-minutes-outage scenario can be nicely implemented, and certainly the specific retrying behavior on the pushing end is critical to make it work. On that front, we have noticed a while back that the default remote_write Prometheus config is suuuper risky in terms of the thundering herd effect. I want to quote from a (private) Wiki page that I created on the topic:

> we need to start tuning the retrying parameters in the pusher Proms (generally in pusher entities), to create and understand the upper bond for the push request rate in view of downtime.

> The pusher prom remote_write retrying parameter defaults are extreme, and explain why a small fleet of pusher proms can DDoS an Opstrace cluster.

> max_shards defaulting to 200. max_backoff defaulting to 100 ms. That means that a loaded single pusher prom is configured to emit 2000 POST HTTP requests per second upon disaster.

> I think we should shift the setup from being something like a pseudo-stream (the current parameters indicate that) to actual batch work with larger batches.

> Where the overhead to payload ratio should play into our favor. That is, I think we want

> much larger capacity
> a lower number of shards
> a much larger batch size
> a much larger send deadline
> a much larger initial retry delay
> a much larger max backoff

> That will decrease the incoming request rate by probably more than one order of magnitude. (edited)

**Comment by nickbp** [comment]
Including another chart since it gave a pretty good illustration of "normal" behavior (right) vs "retry" behavior (left). In effect prometheus was deciding that as soon as the server showed any signs of weakness, it should make the situation worse by increasing the load from ~300qps to ~1700qps (from eyeballing the chart):
![134117748-8513f35e-9e7e-483d-ac18-525d8e78077a](https://user-images.githubusercontent.com/35933/134593339-a774e18d-a394-40e7-91bd-9dfcdd9993c8.png)

I think JP's suggested strategy for making the 5xx->409 remapping more selective makes sense. We could try something like this: if cortex returns a 5xx error, check for a [timestamp](https://prometheus.io/docs/instrumenting/exposition_formats/) of the first entry in the payload and return a 409 if the payload timestamp is not present or is older than (for example) 5 minutes. The server would then have control over whether clients should retry.

The duration value could be adjusted according to how much "look back" we would want to support, making it more of a tradeoff between absolute server-side stability (short or zero duration, effectively the new behavior) vs ability to recover from hiccups (longer duration).

I had been thinking of a quota in the cortex-api pods where they would track of the number of 5xx errors in the last N minutes, and then start returning 409s after that quota had been filled. So for example it might only allow 10k 5xx errors per 10 minutes (avg 16.67qps), and when the quota was filled it would switch to 409 errors as a "safety" to avoid excessive retries. This would be less deterministic in terms of what behavior clients could expect to see, but it could act as a second stop-gap to make sure things always stay within a certain threshold regardless of the number of clients/shards.

Across the two I think we'd sort of have the best of both worlds:
1. The duration based method where we reject old data ("old" being configurable) that results in a 500 error. This would allow new data to retry in the event of brief outages while also ensuring that clients are able to "forget" and move on when things are truly stuck.
2. The count based method where we reject data beyond a certain number of retries. This would act as a last-resort safety measure to keep a cap on retries overall even if there are a lot of active clients/shards. 

FWIW my own opinion is that it _should_ be okay to discard metrics within reason, since they're effectively samples of underlying data taken at a more or less random interval. So if e.g. a few samples get dropped due to a 60s event it shouldn't matter. It wouldn't be good to miss an hour, but a minute or two probably wouldn't even register - for example rate metrics are themselves often smoothed over several minutes anyway. But at the same time, if prometheus is still retrying data from an hour ago and not making progress then that's a problem too. However I think it's different for logs, where you'd really want to not miss things if possible, since that's not just sampling system state on a random interval.

**Comment by nickbp** [comment]
Something I just remembered that might be pertinent is that with the current remapping code, 500 errors (specifically 502 Gateway) due to e.g. a distributor deployment [should still occur](https://github.com/opstrace/opstrace/commit/b48bdae8997ce18a1c707264edc2539a7ef2a178#diff-c08c537964de73b73e863cbc8190e9a4cd7345d3a895bd05a305fec9824ce4e9R66) - those are not filtered out. Instead we only remap 500 errors that were returned by cortex itself.
