### ISSUE TITLE
Build failed with error 141

### ISSUE THREAD

**Issue by sreis** [opstrace/opstrace#164]
**Describe the bug**

```
[2020-12-12T04:08:35Z] md5sum yarn.lock | (cmp -s yarn.lock.md5 - || md5sum yarn.lock > yarn.lock.md5)
[2020-12-12T04:08:35Z] make[1]: *** [Makefile:560: yarn.lock.md5] Error 141
[2020-12-12T04:08:35Z] make[1]: Leaving directory '/build'
[2020-12-12T04:08:35Z] make: *** [Makefile:600: preamble] Error 2
```

https://buildkite.com/opstrace/scheduled-main-builds/builds/1351#e3036dbf-cdf4-475e-97c5-8922f05ba6a7

The [bash docs](https://tldp.org/LDP/abs/html/exitcodes.html) says an exit value above 128 indicates termination due to a signal. If we subtract 128 from the exit code of 141, we get 13, which corresponds to SIGPIPE. The man page for SIGPIPE says, "Broken pipe: write to pipe with no readers.".

**Comment by jgehrcke** [comment]
When we consume infinite data sources like `dev/null` `/dev/random` in a pipeline then it should be obvious that there must be a definite back-propagation mechanism (from right to left, backwards along the pipeline) where later stages in the pipeline can communicate to the earlier stages that "we're done over here! enough! don't send your :hankey: anymore!"

SIGPIPE is usually precisely used as a central elemant in that mechanism; it's how how the later stage tells the previous stage (through the operating system, of course) that it's _done_ consuming with the input, and that is OK for the first stage to not send further input; that it is supposed to exit now, too. Many programs (most programs) therefore have a handler installed for SIGPIPE, and that handler usually initiates _proper_ termination of that very program, with exit code 128.

Another example: when `file.txt` is 10 TB large and we do `cat file.txt | head -n1` then it's that SIGPIPE mechanism which makes `cat` _stop_ reading the file when `head -n1` is done.

Normally the shell considers the exit code of the _last_ command in a pipeline to determine the overall exit code of the pipeline, and this is how the exit code 128 of `cat` in this example will be 'ignored', whereas the exit code 0 of `tail` is what matters; also from the `errexit` option's point of view! 

This changes when we apply the `pipefail` shell option, which we do [in the Makefile](https://github.com/opstrace/opstrace/blob/4e07720b1f3c98c6fafba954237a41bc6d04589e/Makefile#L11) for being a little more strict with catching otherwise unexpected errors:

```
# Dot not ignore errors in piped commands. The goal is to have `make` error
# out upon critical errors like missing files. Example for a critical error
# being swallowed:
#
#    $ cat /tmp/does-not-exist | wc -l
#    cat: /tmp/does-not-exist: No such file or directory
#    0
#    $ echo $?
#    0
#
SHELL=/bin/bash -o pipefail -o errexit -o nounset
```

In 
```
md5sum yarn.lock | (cmp -s yarn.lock.md5 - || md5sum yarn.lock > yarn.lock.md5)
```
there is probably a special case when `yarn.lock.md5` does not exist; in which case the sub shell on the right-hand side does _not_ read from stdin when `md5sum yarn.lock` tries to start writing to the pipe (when `cmp -s yarn.lock.md5 -` has terminated _quickly_).
