### ISSUE TITLE
Build "hibernation" upgrade

### ISSUE THREAD

**Issue by sreis** [opstrace/opstrace#326]
Part of the goal to implement a reliable, testable upgrade strategy to deliver value to users as soon as possible.

# Current Behavior

Upgrades don't handle infrastructure changes and don't handle controller configuration schema changes. The rapid development pace is impacted when handling upgrades since all scenarios (testing, etc...) need to be accounted for during feature development.

# Proposed Behavior

As discussed previously, we will call this new upgrade behavior "hibernation" until a new or better name comes up. 

The proposed solution is to stop all the Kubernetes deployments and destroy the underlying cloud infrastructure *but keep all the data in the cloud storage* (ex, S3 in AWS). Then proceed to rebuild the cloud infrastructure and start all the Kubernetes deployments and attach them to the cloud storage previously used.

The major downside of this approach is that the maintenance window increases. The maintenance window will be the time to destroy and recreate the cloud infrastructure and all Kubernetes deployments, plus the time to propagate the new DNS entries. 

##  Open questions

* To rebuild the cluster, we need to handle any cluster configuration changes that might happen between releases.
* During the cluster rebuild, the DNS entries will require an update. This update will take time to propagate and potentially bring up some issues.
    * What happens to the certificate request during this timeframe? With #151 and #172, we know the certificate request process has issues with retry behavior.
    * What is the behavior of the scraping clients during this timeframe?
* The DNS service, currently, runs a loop every 60 seconds to create and/or destroy DNS entries. After opstrace/dns-service#8 and opstrace/dns-service#9  are there any other issues we need to account for?

**Comment by jgehrcke** [comment]
Adding a bit to this ticket again. "hibernation" would in practice be a special way to tear down an Opstrace instance. Related ticket and prior art: https://github.com/opstrace/opstrace/issues/27

Motivated by https://github.com/opstrace/opstrace/issues/1169 I want to add two quick ideas:

- `opstrace hibernate`, maybe with an option to leave anything ELB and DNS intact so that one does not needlessly lose time if this is being used in the context of an upgrade.
- `opstrace create ... ` (not a new command!) maybe with an option tied to this overall idea of hibernation wakeup; so that this can error out if the prerequisites / state is not found.

In `create` we should then add explicit code that inspects the state of S3, database etc to see if a migration needs to be done (would very rarely be the case).

**Comment by jgehrcke** [comment]
related: https://github.com/opstrace/opstrace/issues/27
