### ISSUE TITLE
cli: "destroy" silently waiting on user confirmation for route53 login

### ISSUE THREAD

**Issue by terrcin** [opstrace/opstrace#353]
**Describe the bug**

The is more a UX thing than anything. I did not associate the destroy command running in the background with a confirmation dialog that popped up in my browser as I was off doing something else on my computer when it occured (which I thought had caused the dialog) and there was no context given in the browser page or in the destroy terminal output telling me what it was about. I hit cancel as a precaution.

**To Reproduce**

I was destroying a cluster in a terminal tab and switched away to do something else leaving it to do it's thing. After a while my browser suddenly took focus and loaded an Opstrace confirmation dialog (cancel and confirm options I think) and showed a unique code for me to check. I don't recall it saying what it was seeking the confirmation for or what had trigered it. I was surprised by this as I wasn't expecting it due to this being my first time deleting a cluster. I visually looked through all my terminal tabs to see if something was waiting and couldn't find anything. I pressed the cancel button as I did not know what it was about.

The `destroy` output was not paused when this happened and was still output things so my initial reaction was that it wasn't this that was seeking my attention to confirm something. After pressing cancel the destroy command failed and exited with the following making me realise it was related:

```
2021-02-11T19:45:29.822Z info: route53: change request status: PENDING
2021-02-11T19:45:30.197Z error: verification failed: User did not confirm their request
2021-02-11T19:45:30.198Z error: DNS service login failed
```

I subsequently checked and found a verification code which had scrolled off screen. 

**Expected behavior**

When the cli is waiting on the user to confirm like this it's output should halt, or if not possible repeatedly output that it is waiting and the confirmation code, or something like that. Maybe even say to check browser. 

In the browser confirmation page, maybe some more text explaining why the user is being prompted. "You have run the cluster delete command and we need confirmation from you before making DNS changes, please check this unique code matches the code in your terminal." or something like that.

**Comment by jgehrcke** [comment]
Yes, I've noticed this myself as a trap -- also @triclambert noticed this.

> When the cli is waiting on the user to confirm like this it's output should halt, or if not possible repeatedly output that it is waiting and the confirmation code, or something like that. Maybe even say to check browser.

I agree. A bit of reasoning: the destroy operation trying to do things concurrently that can be done concurrently. The log output "say to check browser" is there, but it's buried:

```
...
2021-02-12T12:28:02.777Z warning: DNS service client:DELETE failed: Response code 401 (Unauthorized)
2021-02-12T12:28:02.779Z info: perform another login to refresh authentication state
2021-02-12T12:28:02.779Z info: initiate device code login against https://opstrace-dev.us.auth0.com
2021-02-12T12:28:03.034Z info: route53: found hosted zone /hostedzone/Z0638533OOCEE2LJXQGS
2021-02-12T12:28:03.035Z info: route53: get records for zone (not necessarily all of them)
2021-02-12T12:28:03.128Z info: Opening browser to sign in to the Opstrace DNS service in a few seconds. If it does not open, follow this URL: https://opstrace-dev.us.auth0.com/activate?user_code=528-956-113
2021-02-12T12:28:03.129Z info: Verification code: 528-956-113
2021-02-12T12:28:03.258Z info: RDS cluster status: available
2021-02-12T12:28:03.265Z info: EKS cluster status: ACTIVE
...
```

One way to improve on that would be to do the login initially, super early in the `destroy` command's machinery. We prompt for confirmation anyway, i.e. the `destroy` command is interactive by default. But: the login is not always necessary!

What really triggers the login is this:
```
DNS service client:DELETE failed: Response code 401 (Unauthorized)
```
It's only necessary when the locally stored credentials have expired.

This DELETE needs to come "late" in the destroy game (that timing can't be changed).

So, we could do a bit of probing initially, see if those credentials have expired, and then initiate that login basically right after invoking the command, instead of minutes later. They might still be invalid later when actually being used, but that's then a highly unlikely edge case instead of a common case.

> In the browser confirmation page, maybe some more text explaining why the user is being prompted. "You have run the cluster delete command and we need confirmation from you before making DNS changes, please check this unique code matches the code in your terminal." or something like that.

I think that is a great proposal. As long as the browser page popping up relates explicitly to the cluster being destroyed (ideally showing the cluster name) then a lot of this problem is already mitigated.

I think we have two action items here that will  improve the `destroy` experience.

**Comment by triclambert** [comment]
Had this again today.  😅 

> So, we could do a bit of probing initially, see if those credentials have expired, and then initiate that login basically right after invoking the command, instead of minutes later.

This sounds like a great, easy solution to me.

> In the browser confirmation page, maybe some more text explaining why the user is being prompted. 

FYI, we also want to add links to our Privacy Policy and Terms of Service there as well.

**Comment by jgehrcke** [comment]
> One way to improve on that would be to do the login initially

Doing that in a commit on https://github.com/opstrace/opstrace/pull/861
