### ISSUE TITLE
Errors when writing from non-system tenant prometheus

### ISSUE THREAD

**Issue by nickbp** [opstrace/opstrace#478]
Steps to reproduce:
- Go to `https://<tenant>.<me>.opstrace.io/prometheus/`
- Enter a prometheus query into the text box, note that autocompletes actually work fine, implying that some endpoint is reachable to fill the autocomplete text
- Execute the query and get an error like `remote_read: remote server http://cortex-api.dev-tenant.svc.cluster.local:8080/api/v1/read returned HTTP status 401 Unauthorized: Authorization header missing` (my guess: Cortex expects `X-Scope-OrgID=tenantname` header?)

Workarounds:
- If you instead click `Try experimental React UI` in the upper right of the prometheus UI, the charts work fine in there. Maybe that's trying a different query that's successful?

**Comment by jgehrcke** [comment]
What's the goal behind offering `https://<tenant>.<me>.opstrace.io/prometheus/`?

What really is the origin of the HTTP request that is failing with the 401 response? My understanding is that it's the per-tenant Prometheus running in the Opstrace cluster. So, the DNS name `cortex-api.dev-tenant.svc.cluster.local` is indeed valid. And points to the Cortex API proxy. Which requires a tenant API authentication token to be present in the `Authorization` header. Which the Prometheus instance is _not_ configured to provide.

So, the error message `Authorization header missing` really is authoritative and true and helpful -- emitted by our authenticator: https://github.com/opstrace/opstrace/blob/6ff97e0432c8d73e382f79f413ad5f350d2fae37/go/pkg/authenticator/http.go#L35

`remote_read: ....` means that the per-tenant Prometheus tries to subscribe to a remote system via the remote_read protocol.

Things that can be done depending on the actual goal:
* Configure the per-tenant Prometheus to go straight to the Cortex querier system (in which case it must provide the `X-Scope-OrgID` header).
* Configure `https://<tenant>.<me>.opstrace.io/prometheus/` to inherit the authentication system that's used between our web UI frontend and its backend. Make it use a similar query path that the Grafana UI uses (browser -> our web UI backend -> ... -> Cortex querier). That might actually be what happens when "Try experimental React UI".

It's important that between browser and whatever UI we look at the authentication proof is set in a Cookie, and the only thing that's doing that so far is our web UI backend.

**Comment by nickbp** [comment]
A similar error also appears in the `dev-tenant` `prometheus-0` logs, might be related:
```
[...]
ts=2021-03-15T18:42:18.575Z caller=dedupe.go:112 component=remote level=error remote_name=2b7065 url=http://cortex-api.dev-tenant.svc.cluster.local:8080/api/v1/push msg="non-recoverable error" count=1 err="server returned HTTP status 401 Unauthorized: Authorization header missing"
ts=2021-03-15T18:43:18.579Z caller=dedupe.go:112 component=remote level=error remote_name=2b7065 url=http://cortex-api.dev-tenant.svc.cluster.local:8080/api/v1/push msg="non-recoverable error" count=1 err="server returned HTTP status 401 Unauthorized: Authorization header missing"
ts=2021-03-15T18:44:18.583Z caller=dedupe.go:112 component=remote level=error remote_name=2b7065 url=http://cortex-api.dev-tenant.svc.cluster.local:8080/api/v1/push msg="non-recoverable error" count=1 err="server returned HTTP status 401 Unauthorized: Authorization header missing"
ts=2021-03-15T18:45:18.587Z caller=dedupe.go:112 component=remote level=error remote_name=2b7065 url=http://cortex-api.dev-tenant.svc.cluster.local:8080/api/v1/push msg="non-recoverable error" count=1 err="server returned HTTP status 401 Unauthorized: Authorization header missing"
[...]
```

**Comment by nickbp** [comment]
With the above fix, the errors in non-system prometheus logs went away, and I was able to see metrics in non-system tenant grafana. Checked system grafana too, just in case something had regressed in the process, and it was looking fine too.
