### ISSUE TITLE
Add I9n Wizard - an existing I9n can be edited

### ISSUE THREAD

**Issue by terrcin** [opstrace/opstrace#641]
Epic: Onboarding: Add I9n Wizard - K8s Metrics https://github.com/opstrace/opstrace/issues/626

Users can edit I9n, going in and changing their details, for example with the K8s Metrics I9n this could be to add further K8s namespaces to monitor. In this case we'll provide yaml and intstructions for updating their installation not installing it. (Yes these could well be the same thing)

**Comment by nickbp** [comment]
This ticket is still valid - at the moment users can only create new integrations if they want to change something (like credentials, or deploy configs).

It would be useful to be able to update existing I9ns in-place so that input data/dashboards/etc can be preserved with the same `integration_id` UUID.
