### ISSUE TITLE
misc feedback on k8s metrics integration

### ISSUE THREAD

**Issue by triclambert** [opstrace/opstrace#741]
With the understanding that this integration is a preview version, here is some initial feedback.

### Problems

The downloaded file seems to use a `.yml` extension; instead, we should use `.yaml`.

In the downloaded YAML, `name` needs to be indented for Namespace:

```
apiVersion: v1
kind: Namespace
apiVersion: v1
metadata:
name: opstrace-k8s-metrics
```

Or you get an error:

```
> sed "s/__AUTH_TOKEN__/$(cat tenant-api-token-system)/g" opstrace-k8s-metrics.yml | kubectl apply -f -

error: error validating "STDIN": error validating data: ValidationError(Namespace): unknown field "name" in io.k8s.api.core.v1.Namespace; if you choose to ignore these errors, turn validation off with --validate=false
```

The downloaded YAML has the `opstrace.io` domain twice:

```
    - url: https://cortex.system.tracy.opstrace.io.opstrace.io/api/v1/push
```

The "install dashboards" button does not seem to work.

------

### Suggestions

I would like to be able to _uninstall_ an integration as well.  

It might be nice to include the tenant name in the file name—I may have multiple source K8s clusters (prod, staging, dev) and I may want to have the same namespace for collection in each.  Currently, the file name is set to only the namespace name.  You might also include a default preface with "integration-" or something like that.

------

### Just FYI

FYI, from this morning's main build:

```
> ./opstrace --version --log-level debug
b3ab0214-ci
2021-05-17T20:37:39.423Z debug: BUILD_INFO_COMMIT: b3ab0214
2021-05-17T20:37:39.424Z debug: BUILD_INFO_TIME_RFC3339: 2021-05-17 16:09:58+00:00
2021-05-17T20:37:39.425Z debug: BUILD_INFO_HOSTNAME: ip-10-0-2-72.us-west-2.compute.internal
2021-05-17T20:37:39.425Z debug: BUILD_INFO_BRANCH_NAME: main
2021-05-17T20:37:39.426Z debug: shut down logger, then exit with code 0
```

FYI, the collection cluster is GKE.

FYI, the "check status" button was slow to report active, even after many clicks.

FYI, tested with query `process_cpu_seconds_total{integration_id="foo"}`

**Comment by nickbp** [comment]
I think some of these are fixed in the WIP dev branch, but I will do quick fixes for at least the flagrant YAML syntax/content issues right away in main so that they're in a working state there.

**Comment by nickbp** [comment]
Status of items:

Done:
- (done) `yaml` extension: The existing PRs already switched to using `yaml`
- (done) `Namespace` indent: Had been fixed in one of the existing PRs, but a fix has now also been applied to `main`
- (done) double `opstrace.io`: This was an undiscovered bug in the UI/config interation, fixed in `main` as well as in the PRs.
- (done) `install dashboards`: Wasn't implemented in `main` yet, the PR adding support was tested successfully and then merged

Not done:
- Removing an integration: TODO, but I wouldn't be surprised if there was already a tracking issue for this. Per discussion earlier a delete can be performed manually via the Hasura Dashboard UI (not great for users but should be okay for testing/screencast purposes). In other words this may be WAI until the handling for deletion is added.
- Tenant name (or integration name?) in yaml filename: The download filename is handled in the typescript, it is currently hardcoded based on integration type (metrics vs logs)
- Check status button: The status does a query from start=`now-1h` to end=`now`. However I noticed that the calculation for "now" is at page load, rather than at the time the button is pressed, so it doesn't shift forwards as you might expect. As a workaround I updated the query range to be start=`now-1h` to end=`now+1h`, so it should be more consistent about finding new/future data as long as you don't leave the browser window open for >1hr - but again "now" ideally would be recalculated with each status lookup.

**Comment by terrcin** [comment]
I can do the three `not done things`.

With regards to the removing of integrations, do we want to delete dashboards if installed?

**Comment by terrcin** [comment]
#752 - ui: Integration "check status" button should use the current time when clicked
#753 - ui: include Tenant.name in the K8s-Metrcis/Logs yaml download filename
#754 - ui: allow user to delete a previously installed Integration

**Comment by triclambert** [comment]
> do we want to delete dashboards if installed

I would imagine yes.

**Comment by nickbp** [comment]
gonna mark this one closed since the remaining items are now covered by the granular tickets
