### ISSUE TITLE
UI improvement ideas for clarity

### ISSUE THREAD

**Issue by jgehrcke** [opstrace/opstrace#802]
By now, quite a bit of things in the UI are not really intuitively discoverable. I think this can easily be improved by using more expressive labels and maybe a bit of a hierarchy review.

Quick braindump (perfectly disputable ideas):

- Top-left: do not only display the tenant name, but also something like "tenant: " and maybe make it more obvious that this can be switched
- `Overview` exposes system status dashboards for the currently selected tenant, maybe rename to 'system status'. "Overview" is a pretty empty term.
- `Overview -> Logs` is linking to a system status dashboard, maybe rename (_this is not showing logs as "overview -> logs" might suggest_!)
- `Dashboards` is linking to other system dashboards. Should that maybe be buried within the then renamed `Overview` (`System status` section)?
- The top-level `Explore` is non-expressive. The goal here seems to be to have a quick link to the current tenant's logs, and the current tenant's metrics. I think instead of `Explore` we should have one top-level `search metrics` and another one `search logs`, for _that_ tenant's logs/metrics, and it's fine if the corresponding pages then link to the corresponding grafana explore view. (it must be immediately obvious where to click to find "my logs" and "my metrics", and "explore" is not really the best answer I think.)

`Getting Started` view: `What is the System Tenant` is lacking a question mark, and should maybe be on last position. The `Select a Tenant` maybe should be in first position. The headings on that page should be much larger.

**Comment by MatApple** [comment]
> Top-left: do not only display the tenant name, but also something like "tenant: " and maybe make it more obvious that this can be switched

I think we should test this one with people that are unfamiliar to the system. I at first tried this, but it proved to really clutter the dropdown. I'd hesitate to add the "tenant: " clutter since it's really only useful for onboarding - beyond that, once people understand that is the selected tenant, it's unnecessary. Perhaps there is more we can do on the "Getting started page" though to educate about the tenant selection. A guided tour is one idea that comes to mind for a new user.

> Overview exposes system status dashboards for the currently selected tenant, maybe rename to 'system status'. "Overview" is a pretty empty term.

We could rename this to "Tenant Status" if that has more meaning. The idea behind this page is to only show a tenant specific view of high level things you'd care about. I.e. number of active series, ingestion rates for logs/metrics and how close you are to hitting limits. This view is for the user who has access to the tenant (not for the superadmin), and it's to give them enough insight to know their tenant is in good shape (not hitting limits, appears to be healthy (always difficult to quantify), etc). I think our existing dashboard still has to evolve a bit to satisfy the job I'd like it to do here.


> Dashboards is linking to other system dashboards. Should that maybe be buried within the then renamed Overview (System status section)?

This page will show a full tree view of folders and dashboards for the tenant. It will also be where we can show additional metadata for dashboards/folders and (as an intermediate step, a way to sync these to other tenants)

> The top-level Explore is non-expressive

This page will have more data on it, specifically to help explore what metrics exist in the tenant, what log labels exist, etc. We've had quite a bit of feedback about how difficult it is to explore/discover what metrics and log labels actually exist. We'll be able to show some metadata about number of series etc for each metric too.

> Getting Started view: What is the System Tenant is lacking a question mark, and should maybe be on last position. The Select a Tenant maybe should be in first position. The headings on that page should be much larger.

We can definitely adjust the styling on this page!

**Comment by jgehrcke** [comment]
> I think we should test this one with people that are unfamiliar to the system.

Sure. :-)

I knew that there are _multiple tenants I can select from_ and then I was like "where can I do the selection?" 

I had to actively for it, and it took a tiny bit of time, and then I was like "oooh, there in the top-left, this tiny arrow is what I need to use"

Let me be more specific:

- The action of 'switching tenants' isn't as prominently accessible as it could be.
- The answer to 'which tenant is currently selected' isn't as prominently shown as it could be.


> Perhaps there is more we can do on the "Getting started page" though to educate about the tenant selection

Good idea.

> We could rename this to "Tenant Status" if that has more meaning.

Yeah, that goes into the right direction! 'System status', I agree, is pretty generic; however if the top-level menu is _obviously_ tenant-specific, we could just call it "status". Hmm.. but this was really just to trigger thinking. I am stoll not happy with just "status" or "tenant status" or "system status". Maybe something like "activity"?

**Comment by jgehrcke** [comment]
> This page will show a full tree view of folders and dashboards for the tenant. I

:+1: 

> This page will have more data on it, specifically to help explore what metrics exist in the tenant, what log labels exist, etc. We've had quite a bit of feedback about how difficult it is to explore/discover what metrics and log labels actually exist. We'll be able to show some metadata about number of series etc for each metric too.

I might not have gotten my point across. Let me try to tell a UX story:

- I understand that logs and metrics are being pushed into my Opstrace instance for the tenant "prod".
- I visit the UI for the first time, and I want to peek into these logs and metrics.
- I have managed to select the "prod" tenant (and that was already a _tiny_ challenge, because I could not quickly find the drop-down).
- Now I look for a button that says "my logs" or "my metrics". I don't find it.
- I click through all the things, and after all find that "Explore" takes me to where I want to be.

This is really about the limited expressiveness of the word "Explore". For an outsider, it can mean "explore the world, anything". It could mean "Explore Opstrace!". Only for Grafana/Prom users it indicates "Explore _my data_".

To make this maybe a specific UX task:
For someone who does not know our UI yet: selecting a specific tenant and landing in the "my logs" / "my metrics" explore view should take below 10 seconds, and be as intuitive as it can be.

Something like renaming "Explore" to "Explore metrics and logs" might be a helpful first step.

**Comment by MatApple** [comment]
This is good feedback! I wonder what user expectations already exist from other UIs like Grafana for example that has the same "Explore" tab? Whilst we're linking through to Grafana Explore, it does feel like there is a benefit to not changing the name/concept. Perhaps once we bring that "exploration" into our UI, we're in a better position to call it something more specific
